name: k8s manifests validation

on: push

jobs:
  list-manifests:
    runs-on: ubuntu-latest
    outputs:
       matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - id: set-matrix
        run: echo "::set-output name=matrix::$(ls manifests/*.yaml | jq -R -s -c 'split("\n")[:-1]')" 
  kubeval:
     needs: list-manifests
     runs-on: ubuntu-latest
     strategy:
         matrix:
             manifest: ${{ fromJson(needs.list-manifests.outputs.matrix) }}
     steps:
       - uses: actions/checkout@v2.4.2     
       - name: Validate manifests by kubeval 
         uses: instrumenta/kubeval-action@master
         with:
           files: ${{ matrix.manifest }}
